[build]
  functions = "netlify/functions"


[dev]
  command = "npm start" 
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  included_files = [
    "routes/**",
    "mongo/**",
    "package.json",
    "package-lock.json",
    "node_modules/body-parser/**"
  ]